title: "Tanay Nagar"
url: "https://tnagar72.github.io"
baseurl: ""
markdown: kramdown

kramdown:
  parse_block_html: true
  math_engine: katex

collections:
  writing:
    output: true
    permalink: /writing/:path/
  research:
    output: true
    permalink: /research/:path/

defaults:
  - scope:
      path: ""
      type: writing
    values:
      layout: article
  - scope:
      path: ""
      type: research
    values:
      layout: research

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _original
  - NOTES.md
